api_platform:
    # The title of the API.
    title: 'MesCompetence.dev'

    # The description of the API.
    description: 'API description'

    # The version of the API.
    version: '1.0'

    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    patch_formats:
        json: ['application/merge-patch+json']

    swagger:
        versions: [3]
        api_keys:
            Json Web Token:
                name: Authorization
                type: header
    
    defaults:
        pagination_items_per_page: 10
        pagination_client_items_per_page: true